### ISSUE TITLE
Отсутствие компонентного подхода

### ISSUE THREAD

**Issue by akuznetsov-md** [kaluzhniy/mercury#3]
Разработка приложений на React строится на компонентном подходе. Суть его заключается в том, что мы разделяем приложение на самостоятельные элементы интерфейса, исходя из их предназначения:

```
Корневой компонент
- лэйаут страницы
- стили страницы
- функции базовые

Компонент формы авторизации
- лэйаут формы авторизации
- стили формы авторизации
- функции формы авторизации

Компонент профиля пользователя
- лэйаут профиля пользователя
- стили профиля пользователя
- функции профиля пользователя
```

Кстати, БЭМ это тоже про компонентный подход.
Каждый блок = отдельный компонент.

**Comment by kaluzhniy** [comment]
Исправил, посмотри, пожалуйста.
https://github.com/kaluzhniy/mercury/tree/react-form-2

**Comment by kaluzhniy** [comment]
> Разработка приложений на React строится на компонентном подходе. Суть его заключается в том, что мы разделяем приложение на самостоятельные элементы интерфейса, исходя из их предназначения:
> 
> ```
> Корневой компонент
> - лэйаут страницы
> - стили страницы
> - функции базовые
> 
> Компонент формы авторизации
> - лэйаут формы авторизации
> - стили формы авторизации
> - функции формы авторизации
> 
> Компонент профиля пользователя
> - лэйаут профиля пользователя
> - стили профиля пользователя
> - функции профиля пользователя
> ```
> 
> Кстати, БЭМ это тоже про компонентный подход.
> Каждый блок = отдельный компонент.

Исправил, посмотри, пожалуйста.
https://github.com/kaluzhniy/mercury/tree/react-form-2
